services:

  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb
      args:
        - SQL_ROOT_PASSWORD
        - SQL_DATABASE
        - SQL_USER_LOGIN
        - SQL_USER_PASSWORD
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    expose:
      - "3306"

  nginx:
    container_name: nginx
    build: requirements/nginx
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/gurodrig/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/gurodrig/data/mariadb

networks:
  inception:
    name: inception
    driver: bridge
